---
abstract: 'base class for parsing regexes'
author:
  - 'Jeff japhy Pinyan <japhy@perlmonk.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.24, CPAN::Meta::Converter version 2.150010'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Regexp-Parser
no_index:
  directory:
    - t
    - inc
requires:
  Test::More: '0'
resources:
  bugtracker: https://github.com/toddr/Regexp-Parser/issues
  homepage: http://wiki.github.com/toddr/Regexp-Parser
  license: http://dev.perl.org/licenses/
  repository: http://github.com/toddr/Regexp-Parser/tree/master
version: 0.21_01
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
